name: Goalfeed
version: "1.0.4"
slug: goalfeed
description: A service that will provide "goal" events within Home Assistant whenever your favourite MLB or NHL team scores
url: "https://github.com/goalfeed/hassio-goalfeed-repository/tree/main/goalfeed"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false

homeassistant_api: true
options:
  nhl_teams: ""
  mlb_teams: ""
schema:
  mlb_teams: "str?"
  nhl_teams: "str?"
